export {
  GENDERS,
  SUPPORTED_LANGUAGES,
  SPACE_TYPES,
  INDIAN_STATES,
  PHONE_LENGTH,
  PHONE_COUNTRY_CODE,
  PASSWORD_MIN_LENGTH,
  NAME_MIN_LENGTH,
  NAME_MAX_LENGTH,
  ADDRESS_MIN_LENGTH,
  ADDRESS_MAX_LENGTH,
  PINCODE_LENGTH,
} from "@tsp/constants";
